services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler-app
    restart: unless-stopped
    ports:
      - "8001:8001"
      - "3003:8001"
    environment:
      - NODE_ENV=production
      - PORT=8001
    networks:
      - scheduler-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8001/api/days', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  scheduler-network:
    driver: bridge
